"""Initial migration

Revision ID: cb75acdb9616
Revises: 
Create Date: 2025-03-17 10:01:16.811288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb75acdb9616'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lobbies',
    sa.Column('lobbyname', sa.String(), nullable=False),
    sa.Column('players', sa.JSON(), nullable=True),
    sa.Column('stage', sa.Enum('WAITING', 'ACTIVE', 'COMPLETED', name='lobbystage'), server_default=sa.text("'WAITING'"), nullable=False),
    sa.Column('winner', sa.Enum('NODEFINED', 'DRAW', 'PLAYER1', 'PLAYER2', name='winners'), server_default=sa.text("'NODEFINED'"), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patches',
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('games', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('patches')
    op.drop_table('lobbies')
    # ### end Alembic commands ###
