"""Initial migration

Revision ID: b7545c93d7f2
Revises: 
Create Date: 2025-06-11 22:53:33.368898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7545c93d7f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lobbies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('players', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('field', sa.JSON(), nullable=False),
    sa.Column('gametype', sa.Enum('INFINITY_TIC_TAC_TOE', name='gametype'), nullable=False),
    sa.Column('state', sa.Enum('WAITING', 'ACTIVE', 'COMPLETED', name='lobbystage'), server_default=sa.text("'COMPLETED'"), nullable=False),
    sa.Column('time_create', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='roles'), server_default=sa.text("'USER'"), nullable=False),
    sa.Column('isActive', sa.Boolean(), server_default=sa.text("'True'"), nullable=False),
    sa.Column('time_create', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('loses', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('users')
    op.drop_table('lobbies')
    # ### end Alembic commands ###
